# Server Settings
PORT: 8080

# Mongo URI to access our database
MONGO_URI: ""

# Security Configurations
JWT_SECRET_KEY: "HotDogStanleyWithSomeBeans"

# Spotify Credentials
SPOTIFY_CLIENT_ID: f0
SPOTIFY_CLIENT_SECRET: f1